include:
  - project: $CI_INCLUDE_PATH
    ref: $CI_INCLUDE_REF
    file:
      - "/variables-subchart.gitlab-ci.yml"

  - project: $CI_INCLUDE_PATH
    ref: $CI_INCLUDE_REF
    file:
      - "/test-subchart.gitlab-ci.yml"

  - project: $CI_INCLUDE_PATH
    ref: $CI_INCLUDE_REF
    file:
      - "/publish-subchart.gitlab-ci.yml"

  - project: $CI_INCLUDE_PATH
    ref: $CI_INCLUDE_REF
    file:
      - "/sign-subchart.gitlab-ci.yml"

variables:
  KUBECONFORM_SKIP_KINDS_DEFAULT: "Alert,ArtifactGenerator,Bucket,ExternalArtifact,GitRepository,HelmChart,HelmRelease,HelmRepository,ImagePolicy,ImageRepository,ImageUpdateAutomation,Kustomization,OCIRepository,Provider,Receiver"

stages:
  - lint
  - tests

  - validate-tag
  - package
  - publish

  - sign
  - metadata
  - verify
